plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.healthapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.healthapp"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // 无 androidx 依赖，使用 Android 系统原生 API
}
